Update TV.yml

diff --git a/.github/workflows/TV.yml b/.github/workflows/TV.yml
--- a/.github/workflows/TV.yml
+++ b/.github/workflows/TV.yml
@@ -41,6 +41,19 @@ jobs:
         with:
           fetch-depth: 0
       
+      - name: Find ZIP file in the repository
+        run: |
+          # 假设你的.zip文件在build目录下
+          ZIP_PATH="$GITHUB_WORKSPACE/tv-apk/${{ matrix.branchName }}_*.apk"
+          
+          # 检查文件是否存在
+          if [ -f "$ZIP_PATH" ]; then
+            echo "ZIP file found at: $ZIP_PATH"
+            # 在这里你可以对ZIP文件执行任何你需要的操作，比如解压缩、检查内容等
+          else
+            echo "ZIP file not found at: $ZIP_PATH"
+            exit 1
+          fi
       - name: Check New Commit
         run: |
           upStream=https://github.com/${{ matrix.userName }}/${{ matrix.repoName }}
